export const RELEASE_LIST_REQUEST = 'RELEASE_LIST_REQUEST'
export const RELEASE_LIST_SUCCESS = 'RELEASE_LIST_SUCCESS'
export const RELEASE_LIST_FAIL = 'RELEASE_LIST_FAIL'

export const RELEASE_DETAILS_REQUEST = 'RELEASE_DETAILS_REQUEST'
export const RELEASE_DETAILS_SUCCESS = 'RELEASE_DETAILS_SUCCESS'
export const RELEASE_DETAILS_FAIL = 'RELEASE_DETAILS_FAIL'

export const RELEASE_DELETE_REQUEST = 'RELEASE_DELETE_REQUEST'
export const RELEASE_DELETE_SUCCESS = 'RELEASE_DELETE_SUCCESS'
export const RELEASE_DELETE_FAIL = 'RELEASE_DELETE_FAIL'

export const RELEASE_CREATE_REQUEST = 'RELEASE_CREATE_REQUEST'
export const RELEASE_CREATE_SUCCESS = 'RELEASE_CREATE_SUCCESS'
export const RELEASE_CREATE_FAIL = 'RELEASE_CREATE_FAIL'
export const RELEASE_CREATE_RESET = 'RELEASE_CREATE_RESET'

export const RELEASE_UPDATE_REQUEST = 'RELEASE_UPDATE_REQUEST'
export const RELEASE_UPDATE_SUCCESS = 'RELEASE_UPDATE_SUCCESS'
export const RELEASE_UPDATE_FAIL = 'RELEASE_UPDATE_FAIL'
export const RELEASE_UPDATE_RESET = 'RELEASE_UPDATE_RESET'
